# Generated by Django 4.2.20 on 2025-03-19 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreview',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
