# Generated by Django 4.2.20 on 2025-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
